### ISSUE TITLE
Unable to publish a library

### ISSUE THREAD

**Issue by kEllieGit** [Facepunch/sbox-issues#6410]
### Describe the bug

I am trying to publish my library to Sbox.game, but it keeps compile failing at the publish part!
Here is the github repository with the library I try to publish in it:
[https://github.com/kEllieGit/SBox-Visual-Novel-Base](https://github.com/kEllieGit/SBox-Visual-Novel-Base)

### To Reproduce

Trying to publish a library to sbox.game, but it keeps throwing the following error:
```
[GameMenu] Compiling failed. Can't continue.	System.InvalidOperationException: Compiling failed. Can't continue.
   at Editor.EditorUtility.Projects.Compile(Project project, Action`1 logOutput) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Utility\Utility.Projects.Compile.cs:line 126
   at Editor.ProjectSettingPages.PublishPage.CompileWizardPage.DoProjectCompile() in E:\SteamLibrary\steamapps\common\sbox\addons\tools\Code\Editor\ProjectSettings\Publish\PublishPage.2a.Compile.cs:line 77
   at Editor.ProjectSettingPages.PublishPage.CompileWizardPage.Refresh() in E:\SteamLibrary\steamapps\common\sbox\addons\tools\Code\Editor\ProjectSettings\Publish\PublishPage.2a.Compile.cs:line 45
```

### Expected behavior

The library should publish as expected.

### Media/Files

Below is my log file. It keeps spewing about conflicting types for w/e reason, then fails to compile.
[Log.log](https://github.com/user-attachments/files/16981679/Log.log)

**Comment by kEllieGit** [comment]
Caused by #6414, having extension methods in your library fails to let it compile for upload.
I removed my extension methods and suddenly I could publish with no issue.
